using Newtonsoft.Json;
using System;
using System.IO;
using System.Linq;

namespace MagicBalanceConfigurator.Generators
{
    public class ItemModsProvider
    {
        public static ItemMod[] ItemMods { get; private set; } = new ItemMod[] { };
        public static string[] ItemsPrefixes { get; set; } = new string[] { };
        public static string[] ItemsAfixes { get; set; } = new string[] { };
        public static string[] ItemsSufixes { get; set; } = new string[] { };

        public const string HpUnequipStr = "if((self.attribute[1] - [Value]) <= 0) { self.attribute[1] = 1; } else { self.attribute[1] -= [Value]; }";

        public static void InitializeItemsMods()
        {
            if (!IsItemModsConfigsExist())
            {
                ItemMods = GetDefaultMods();
                UpdateItemsMods();
            }
            string raw = File.ReadAllText(Consts.ItemModsConfigsPath);
            ItemsModsContainer itemsModsContainer = JsonConvert.DeserializeObject<ItemsModsContainer>(raw);
            ItemMods = itemsModsContainer.ItemMods;
            ItemsPrefixes = itemsModsContainer.ItemsPrefixes;
            ItemsAfixes = itemsModsContainer.ItemsAfixes;
            ItemsSufixes = itemsModsContainer.ItemsSufixes;
        }

        public static void UpdateItemsMods()
        {
            ItemsModsContainer itemsModsContainer = new ItemsModsContainer() 
            { 
                ItemMods = ItemMods,
                ItemsAfixes = ItemsAfixes, 
                ItemsPrefixes = ItemsPrefixes, 
                ItemsSufixes = ItemsSufixes 
            };
            string raw = JsonConvert.SerializeObject(itemsModsContainer);
            File.WriteAllText(Consts.ItemModsConfigsPath, raw);
        }

        public static bool IsItemModsConfigsExist() => File.Exists(Consts.ItemModsConfigsPath);

        public static ItemMod GetModByName(string name) => ItemMods.FirstOrDefault(x => x.ModName == name);

        private static ItemMod[] GetDefaultMods()
        {
            return new ItemMod[]
            {
                new ItemMod(1, 1 ,3) {ModName = "Mana regeneration", Template_Text = "StExt_str_JwlrOpt_ManaRegen", ModRarity = 15,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_ManaRegen")};\r\n\t\tStExt_Jwlr_ManaRegen += [Value]", Template_OnUnequip = "StExt_Jwlr_ManaRegen -= [Value]"  },
                new ItemMod(2, 5, 15) { ModName = "Summon HP bonus", Template_Text = "StExt_Str_ShowWeapStats_SumHp", ModRarity = 30,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_ShowWeapStats_SumHp")};\r\n\t\tStExt_SumBonus_Hp += [Value]", Template_OnUnequip = "StExt_SumBonus_Hp -= [Value]"  },
                new ItemMod(3, 3, 9) { ModName = "Summon stats bonus", Template_Text = "StExt_Str_ShowWeapStats_SumPwr", ModRarity = 30,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_ShowWeapStats_SumPwr")};\r\n\t\tStExt_SumBonus_Stats += [Value]", Template_OnUnequip = "StExt_SumBonus_Stats -= [Value]"  },
                new ItemMod(4, 3, 9) { ModName = "Summon protection bonus", Template_Text = "StExt_Str_ShowWeapStats_SumProt", ModRarity = 30,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_ShowWeapStats_SumProt")};\r\n\t\tStExt_SumBonus_Prot += [Value]", Template_OnUnequip = "StExt_SumBonus_Prot -= [Value]"  },
                new ItemMod(5, 4, 12) { ModName = "Energy shield regen", Template_Text = "StExt_str_JwlrOpt_EsRegen", ModRarity = 30,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_EsRegen")};\r\n\t\tStExt_Jwlr_EsRegen += [Value]", Template_OnUnequip = "StExt_Jwlr_EsRegen -= [Value]"  },
                new ItemMod(6, 1, 15) { ModName = "Luck", Template_Text = "StExt_Str_ShowWeapStats_Luck", ModRarity = 10,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_ShowWeapStats_Luck")};\r\n\t\tStExt_LootBonus += [Value]", Template_OnUnequip = "StExt_LootBonus -= [Value]" },
                new ItemMod(7, 5, 10) { ModName = "Str + Agility", Template_Text = "StExt_str_JwlrOpt_Stats", ModRarity = 25,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_Stats")};\r\n\t\tnpc_changeattribute(self, atr_dexterity, [Value]);\r\n\t\tnpc_changeattribute(self, atr_strength, [Value])", Template_OnUnequip = "npc_changeattribute(self, atr_dexterity, -[Value]);\r\n\t\tnpc_changeattribute(self, atr_strength, -[Value])" },
                new ItemMod(8, 10, 30) { ModName = "Mana", Template_Text = "name_bonus_manamax", ModRarity = 70,
                    Template_OnEquip = $"{ModEquipInfoString("name_bonus_manamax")};\r\n\t\tself.attribute[3] += [Value]", Template_OnUnequip = "self.attribute[3] -= [Value]" },
                new ItemMod(9, 10, 30) { ModName = "Hp", Template_Text = "name_bonus_hpmax", ModRarity = 70,
                    Template_OnEquip = $"{ModEquipInfoString("name_bonus_hpmax")};\r\n\t\tself.attribute[1] += [Value]", Template_OnUnequip = HpUnequipStr },
                new ItemMod(10, 5, 20) { ModName = "Hp + Mana", Template_Text = "StExt_str_JwlrOpt_StatsHpMp", ModRarity = 35,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_StatsHpMp")};\r\n\t\tself.attribute[1] += [Value];\r\n\t\tself.attribute[3] += [Value]", Template_OnUnequip = $"{HpUnequipStr};\r\n\t\tself.attribute[3] -= [Value]" },
                new ItemMod(11, 5, 20) { ModName = "Int", Template_Text = "StExt_str_JwlrOpt_Int", ModRarity = 50,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_Int")};\r\n\t\trx_changeintquiet([Value])", Template_OnUnequip = "rx_changeintquiet(-[Value])" },
                new ItemMod(12, 15, 35) { ModName = "Energy shield", Template_Text = "StExt_str_JwlrOpt_Es", ModRarity = 50,
                    Template_OnEquip  = $"{ModEquipInfoString("StExt_str_JwlrOpt_Es")};\r\n\t\tStExt_Jwlr_Es += [Value]", Template_OnUnequip = "StExt_Jwlr_Es -= [Value]" },
                new ItemMod(13, 5, 10) { ModName = "Magic + Fire protection", Template_Text = "StExt_str_JwlrOpt_ProtMagic", ModRarity = 15,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_ProtMagic")};\r\n\t\tself.protection[5] += [Value];\r\n\t\tself.protection[3] += [Value]", Template_OnUnequip = "self.protection[5] -= [Value];\r\n\t\tself.protection[3] -= [Value]" },
                new ItemMod(14, 5, 10) { ModName = "Physics protection", Template_Text = "StExt_str_JwlrOpt_ProtWeap", ModRarity = 15,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_ProtWeap")};\r\n\t\tself.protection[6] += [Value];\r\n\t\tself.protection[2] += [Value];\r\n\t\tself.protection[1] += [Value]", Template_OnUnequip = "self.protection[6] -= [Value];\r\n\t\tself.protection[2] -= [Value];\r\n\t\tself.protection[1] -= [Value]" },
                new ItemMod(15, 10, 20) { ModName = "Point protection", Template_Text = "rx_inv_descarmor_prot_point", ModRarity = 40,
                    Template_OnEquip = $"{ModEquipInfoString("rx_inv_descarmor_prot_point")};\r\n\t\tself.protection[6] += [Value]", Template_OnUnequip = "self.protection[6] -= [Value]" },
                new ItemMod(16, 10, 20) { ModName = "Edge protection", Template_Text = "rx_inv_descarmor_prot_edge", ModRarity = 40,
                    Template_OnEquip = $"{ModEquipInfoString("rx_inv_descarmor_prot_edge")};\r\n\t\tself.protection[2] += [Value]", Template_OnUnequip = "self.protection[2] -= [Value]" },
                new ItemMod(17, 10, 20) { ModName = "Blunt protection", Template_Text = "rx_inv_descarmor_prot_blunt", ModRarity = 40,
                    Template_OnEquip = $"{ModEquipInfoString("rx_inv_descarmor_prot_blunt")};\r\n\t\tself.protection[1] += [Value]", Template_OnUnequip = "self.protection[1] -= [Value]" },
                new ItemMod(18, 10, 20) { ModName = "Fly protection", Template_Text = "rx_shield_endurancelevel_str", ModRarity = 40,
                    Template_OnEquip = $"{ModEquipInfoString("rx_shield_endurancelevel_str")};\r\n\t\tself.protection[4] += [Value]", Template_OnUnequip = "self.protection[4] -= [Value]" },
                new ItemMod(19, 10, 20) { ModName = "Fire protection", Template_Text = "rx_inv_descarmor_prot_fire", ModRarity = 40,
                    Template_OnEquip = $"{ModEquipInfoString("rx_inv_descarmor_prot_fire")};\r\n\t\tself.protection[3] += [Value]", Template_OnUnequip = "self.protection[3] -= [Value]" },
                new ItemMod(20, 10, 20) { ModName = "Magic protection", Template_Text = "rx_inv_descarmor_prot_magic", ModRarity = 40,
                    Template_OnEquip = $"{ModEquipInfoString("rx_inv_descarmor_prot_magic")};\r\n\t\tself.protection[5] += [Value]", Template_OnUnequip = "self.protection[5] -= [Value]" },
                new ItemMod(21, 1, 2) { ModName = "Hp regeneration", Template_Text = "StExt_str_JwlrOpt_HpRegen", ModRarity = 25,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_HpRegen")};\r\n\t\tStExt_Jwlr_HpRegen += [Value]", Template_OnUnequip = "StExt_Jwlr_HpRegen -= [Value]"  },
                new ItemMod(22, 1, 1) { ModName = "Max summons", Template_Text = "StExt_Str_ShowWeapStats_SumCount", ModRarity = 15,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_ShowWeapStats_SumCount")};\r\n\t\tStExt_Jwlr_SumCount += [Value]", Template_OnUnequip = "StExt_Jwlr_SumCount -= [Value]"  },
                new ItemMod(23, 1, 2) { ModName = "Dodge chance", Template_Text = "StExt_str_JwlrOpt_Dodge", ModRarity = 40,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_Dodge")};\r\n\t\tStExt_Jwlr_DodgeChance += [Value]", Template_OnUnequip = "StExt_Jwlr_DodgeChance -= [Value]" },
                new ItemMod(24, 15, 30) { ModName = "Energy shield barrier", Template_Text = "StExt_str_JwlrOpt_EsBarier", ModRarity = 30,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_EsBarier")};\r\n\t\tStExt_Jwlr_EsBarrier += [Value]", Template_OnUnequip = "StExt_Jwlr_EsBarrier -= [Value]" },
                new ItemMod(25, 3, 9) { ModName = "Speed modifier", Template_Text = "StExt_str_JwlrOpt_SpeedMod", ModRarity = 10,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_SpeedMod")};\r\n\t\tadditionalacceleration += [Value]", Template_OnUnequip = "additionalacceleration -= [Value]" },
                new ItemMod(26, 1, 3) { ModName = "2H bonus", Template_Text = "StExt_str_JwlrOpt_2hBonus", ModRarity = 20,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_2hBonus")};\r\n\t\tb_addfightskill(self, npc_talent_2h, [Value])", Template_OnUnequip = "b_addfightskill(self, npc_talent_2h, -[Value])" },
                new ItemMod(27, 1, 3) { ModName = "1H bonus", Template_Text = "StExt_str_JwlrOpt_1hBonus", ModRarity = 20,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_1hBonus")};\r\n\t\tb_addfightskill(self, npc_talent_1h, [Value])", Template_OnUnequip = "b_addfightskill(self, npc_talent_1h, -[Value])" },
                new ItemMod(28, 1, 3) { ModName = "Bow bonus", Template_Text = "StExt_str_JwlrOpt_BowBonus", ModRarity = 20,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_BowBonus")};\r\n\t\tb_addfightskill(self, npc_talent_bow, [Value])", Template_OnUnequip = "b_addfightskill(self, npc_talent_bow, -[Value])" },
                new ItemMod(29, 1, 3) { ModName = "Crossbow bonus", Template_Text = "StExt_str_JwlrOpt_CrossbowBonus", ModRarity = 20,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_CrossbowBonus")};\r\n\t\tb_addfightskill(self, npc_talent_crossbow, [Value])", Template_OnUnequip = "b_addfightskill(self, npc_talent_crossbow, -[Value])" },
                new ItemMod(30, 10, 50) { ModName = "Aura bonus", Template_Text = "StExt_str_Jwlr_AuraPwrDist", ModRarity = 20,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_Jwlr_AuraPwrDist")};\r\n\t\tStExt_Jwlr_AuraPwrDist += [Value]", Template_OnUnequip = "StExt_Jwlr_AuraPwrDist -= [Value]" },
                new ItemMod(31, 1, 1) { ModName = "Poision immune", Template_Text = "StExt_str_Jwlr_PoisionResist", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_Jwlr_PoisionResist")};\r\n\t\tStExt_Jwlr_PoisionResist += [Value]", Template_OnUnequip = "StExt_Jwlr_PoisionResist -= [Value]" },
                new ItemMod(32, 1, 1) { ModName = "Curse immune", Template_Text = "StExt_str_Jwlr_CurseResist", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_Jwlr_CurseResist")};\r\n\t\tStExt_Jwlr_CurseResist += [Value]", Template_OnUnequip = "StExt_Jwlr_CurseResist -= [Value]" },
                new ItemMod(33, 10, 25) { ModName = "Death magic bonus", Template_Text = "StExt_Str_DeathMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_DeathMasteryDamage")};\r\n\t\tStExt_Jwlr_DeathMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_DeathMasteryDamage -= [Value]" },
                new ItemMod(34, 10, 25) { ModName = "Life magic bonus", Template_Text = "StExt_Str_LifeMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_LifeMasteryDamage")};\r\n\t\tStExt_Jwlr_LifeMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_LifeMasteryDamage -= [Value]" },
                new ItemMod(35, 10, 25) { ModName = "Light magic bonus", Template_Text = "StExt_Str_LightMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_LightMasteryDamage")};\r\n\t\tStExt_Jwlr_LightMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_LightMasteryDamage -= [Value]" },
                new ItemMod(36, 10, 25) { ModName = "Dark magic bonus", Template_Text = "StExt_Str_DarkMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_DarkMasteryDamage")};\r\n\t\tStExt_Jwlr_DarkMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_DarkMasteryDamage -= [Value]" },
                new ItemMod(37, 10, 25) { ModName = "Electric magic bonus", Template_Text = "StExt_Str_ElectricMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_ElectricMasteryDamage")};\r\n\t\tStExt_Jwlr_ElectricMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_ElectricMasteryDamage -= [Value]" },
                new ItemMod(38, 10, 25) { ModName = "Air magic bonus", Template_Text = "StExt_Str_AirMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_AirMasteryDamage")};\r\n\t\tStExt_Jwlr_AirMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_AirMasteryDamage -= [Value]" },
                new ItemMod(39, 10, 25) { ModName = "Earth magic bonus", Template_Text = "StExt_Str_EarthMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_EarthMasteryDamage")};\r\n\t\tStExt_Jwlr_EarthMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_EarthMasteryDamage -= [Value]" },
                new ItemMod(40, 10, 25) { ModName = "Ice magic bonus", Template_Text = "StExt_Str_IceMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_IceMasteryDamage")};\r\n\t\tStExt_Jwlr_IceMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_IceMasteryDamage -= [Value]" },
                new ItemMod(41, 10, 25) { ModName = "Fire magic bonus", Template_Text = "StExt_Str_FireMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_FireMasteryDamage")};\r\n\t\tStExt_Jwlr_FireMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_FireMasteryDamage -= [Value]" },
                new ItemMod(42, 15, 45) { ModName = "Weapon damage", Template_Text = "StExt_Str_WeapDam", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeapDam")};\r\n\t\tStExt_Jwlr_WeapDam += [Value]", Template_OnUnequip = "StExt_Jwlr_WeapDam -= [Value]" },
                new ItemMod(43, 2, 4) { ModName = "Magic power", Template_Text = "StExt_Str_MagicPower", ModRarity = 3,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_MagicPower")};\r\n\t\tcountlearnspell += [Value]", Template_OnUnequip = "countlearnspell -= [Value]" },
                new ItemMod(44, 10, 25) { ModName = "Golem magic bonus", Template_Text = "StExt_Str_GolemMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_GolemMasteryDamage")};\r\n\t\tStExt_Jwlr_GolemMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_GolemMasteryDamage -= [Value]" },
                new ItemMod(45, 10, 25) { ModName = "Demon magic bonus", Template_Text = "StExt_Str_DemonMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_DemonMasteryDamage")};\r\n\t\tStExt_Jwlr_DemonMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_DemonMasteryDamage -= [Value]" },


                new ItemMod(101, 50, 250) { ModName = "Potion Hp", Template_Text = "StExt_Str_Alch_HpRestore", ModRarity = 75,
                    Template_OnEquip = "npc_changeattribute(self, atr_hitpoints, [Value]);\r\n\t\tif(self.attribute > self.attribute[1]) { self.attribute = self.attribute[1]; }" },
                new ItemMod(102, 25, 125) { ModName = "Potion Hp debuf", Template_Text = "StExt_Str_Alch_HpRestoreDebuf", ModRarity = 75,
                    Template_OnEquip = "npc_changeattribute(self, atr_hitpoints, -[Value])" },
                new ItemMod(103, 5, 15) { ModName = "Potion Hp perc", Template_Text = "StExt_Str_Alch_HpRestorePerc", ModRarity = 25,
                    Template_OnEquip = "rx_restorehealthpercent(self, [Value])" },
                new ItemMod(104, 3, 9) { ModName = "Potion Hp perc debuf", Template_Text = "StExt_Str_Alch_HpRestorePercDebuf", ModRarity = 25,
                    Template_OnEquip = "rx_restorehealthpercent(self, -[Value])" },
                new ItemMod(105, 30, 150) { ModName = "Potion Mp", Template_Text = "StExt_Str_Alch_MpRestore", ModRarity = 75,
                    Template_OnEquip = "npc_changeattribute(self, atr_mana, [Value]);\r\n\t\tif(self.attribute[2] > self.attribute[3]) { self.attribute[2] = self.attribute[3]; }" },
                new ItemMod(106, 20, 100) { ModName = "Potion Mp debuf", Template_Text = "StExt_Str_Alch_MpRestoreDebuf", ModRarity = 75,
                    Template_OnEquip = "npc_changeattribute(self, atr_mana, -[Value])" },
                new ItemMod(107, 5, 15) { ModName = "Potion Mp perc", Template_Text = "StExt_Str_Alch_MpRestorePerc", ModRarity = 25,
                    Template_OnEquip = "rx_restoremanapercent([Value])" },
                new ItemMod(108, 3, 9) { ModName = "Potion Mp perc debuf", Template_Text = "StExt_Str_Alch_MpRestorePercDebuf", ModRarity = 25,
                    Template_OnEquip = "rx_restoremanapercent(-[Value])" },
                new ItemMod(109, 5, 15) { ModName = "Potion Stam perc", Template_Text = "StExt_Str_Alch_StamRestorePerc", ModRarity = 50,
                    Template_OnEquip = "rx_restorestaminapercent([Value])" },
                new ItemMod(110, 3, 9) { ModName = "Potion Stam perc debuf", Template_Text = "StExt_Str_Alch_StamRestorePercDebuf", ModRarity = 50,
                    Template_OnEquip = "rx_restorestaminapercent(-[Value])" },
                new ItemMod(111, 50, 150) { ModName = "Potion Stam", Template_Text = "StExt_Str_Alch_StamRestore", ModRarity = 75,
                    Template_OnEquip = "rx_restorestamina([Value])" },
                new ItemMod(112, 30, 90) { ModName = "Potion Stam debuf", Template_Text = "StExt_Str_Alch_StamRestoreDebuf", ModRarity = 75,
                    Template_OnEquip = "rx_restorestamina(-[Value])" },
                new ItemMod(113, 60, 120) { ModName = "Potion sprint", Template_Text = "StExt_Str_Alch_Sprint", ModRarity = 25,
                    Template_OnEquip = "rx_applysprint([Value])" },
                new ItemMod(114, 15, 50) { ModName = "Potion str", Template_Text = "StExt_PotionEffect_ExtraStr_potion_str", ModRarity = 25,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_ExtraStr, [Value], [Duration])" },
                new ItemMod(115, 15, 50) { ModName = "Potion agi", Template_Text = "StExt_PotionEffect_ExtraAgi_potion_str", ModRarity = 25,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_ExtraAgi, [Value], [Duration])" },
                new ItemMod(116, 15, 50) { ModName = "Potion long hp", Template_Text = "StExt_PotionEffect_ExtraHp_potion_str", ModRarity = 25,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_ExtraHp, [Value], [Duration])" },
                new ItemMod(117, 5, 25) { ModName = "Potion long hp debuf", Template_Text = "StExt_PotionEffect_ExtraHpDebuff_potion_str", ModRarity = 15,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_ExtraHp, -[Value], [Duration])" },
                new ItemMod(118, 15, 50) { ModName = "Potion long mp", Template_Text = "StExt_PotionEffect_ExtraMana_potion_str", ModRarity = 25,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_ExtraMana, [Value], [Duration])" },
                new ItemMod(119, 5, 25) { ModName = "Potion long mp debuf", Template_Text = "StExt_PotionEffect_ExtraManaDebuff_potion_str", ModRarity = 15,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_ExtraMana, -[Value], [Duration])" },
                new ItemMod(120, 15, 50) { ModName = "Potion int", Template_Text = "StExt_PotionEffect_ExtraInt_potion_str", ModRarity = 25,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_ExtraInt, [Value], [Duration])" },
                new ItemMod(121, 2, 6) { ModName = "Potion hp regen", Template_Text = "StExt_PotionEffect_HpRegen_potion_str", ModRarity = 15,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_HpRegen, [Value], [Duration])" },
                new ItemMod(122, 2, 6) { ModName = "Potion mp regen", Template_Text = "StExt_PotionEffect_ManaReg_potion_str", ModRarity = 15,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_ManaReg, [Value], [Duration])" },
                new ItemMod(123, 3, 9) { ModName = "Potion stam regen", Template_Text = "StExt_PotionEffect_StamRegen_potion_str", ModRarity = 35,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_StamRegen, [Value], [Duration])" },
                new ItemMod(124, 10, 30) { ModName = "Potion es regen", Template_Text = "StExt_PotionEffect_EsRegen_potion_str", ModRarity = 30,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_EsRegen, [Value], [Duration])" },
                new ItemMod(125, 50, 150) { ModName = "Potion es", Template_Text = "StExt_PotionEffect_ExtraEs_potion_str", ModRarity = 40,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_ExtraEs, [Value], [Duration])" },
                new ItemMod(126, 10, 25) { ModName = "Potion weap prot", Template_Text = "StExt_PotionEffect_ExtraWeapProt_potion_str", ModRarity = 45,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_ExtraWeapProt, [Value], [Duration])" },
                new ItemMod(127, 15, 25) { ModName = "Potion magic prot", Template_Text = "StExt_PotionEffect_ExtraMagicProt_potion_str", ModRarity = 60,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_ExtraMagicProt, [Value], [Duration])" },
                new ItemMod(128, 15, 25) { ModName = "Potion fire prot", Template_Text = "StExt_PotionEffect_ExtraFireProt_potion_str", ModRarity = 60,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_ExtraFireProt, [Value], [Duration])" },
                new ItemMod(129, 15, 50) { ModName = "Potion fly prot", Template_Text = "StExt_PotionEffect_ExtraFlyProt_potion_str", ModRarity = 50,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_ExtraFlyProt, [Value], [Duration])" },
                new ItemMod(130, 5, 15) { ModName = "Potion speed", Template_Text = "StExt_PotionEffect_ExtraSpeed_potion_str", ModRarity = 5,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_ExtraSpeed, [Value], [Duration])" },
                new ItemMod(131, 10, 30) { ModName = "Potion sum heal", Template_Text = "StExt_PotionEffect_SumHeal_potion_str", ModRarity = 25,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_SumHeal, [Value], [Duration])" },
                new ItemMod(132, 1, 3) { ModName = "Potion dodge", Template_Text = "StExt_PotionEffect_Dodge_potion_str", ModRarity = 5,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_Dodge, [Value], [Duration])" },
                new ItemMod(133, 15, 50) { ModName = "Potion luck", Template_Text = "StExt_PotionEffect_Luck_potion_str", ModRarity = 25,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_Luck, [Value], [Duration])" },
                new ItemMod(134, 1, 3) { ModName = "Potion magic pwr", Template_Text = "StExt_PotionEffect_MagicPwr_potion_str", ModRarity = 5,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_MagicPwr, [Value], [Duration])" },
                new ItemMod(135, 50, 150) { ModName = "Potion weap damage", Template_Text = "StExt_PotionEffect_WeapDam_potion_str", ModRarity = 10,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_WeapDam, [Value], [Duration])" },
                new ItemMod(136, 15, 50) { ModName = "Potion fire mastery", Template_Text = "StExt_PotionEffect_FireMasteryDamage_potion_str", ModRarity = 10,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_FireMasteryDamage, [Value], [Duration])" },
                new ItemMod(137, 15, 50) { ModName = "Potion ice mastery", Template_Text = "StExt_PotionEffect_IceMasteryDamage_potion_str", ModRarity = 10,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_IceMasteryDamage, [Value], [Duration])" },
                new ItemMod(138, 15, 50) { ModName = "Potion earth mastery", Template_Text = "StExt_PotionEffect_EarthMasteryDamage_potion_str", ModRarity = 10,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_EarthMasteryDamage, [Value], [Duration])" },
                new ItemMod(139, 15, 50) { ModName = "Potion air mastery", Template_Text = "StExt_PotionEffect_AirMasteryDamage_potion_str", ModRarity = 10,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_AirMasteryDamage, [Value], [Duration])" },
                new ItemMod(140, 15, 50) { ModName = "Potion electro mastery", Template_Text = "StExt_PotionEffect_ElectricMasteryDamage_potion_str", ModRarity = 10,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_ElectricMasteryDamage, [Value], [Duration])" },
                new ItemMod(141, 15, 50) { ModName = "Potion darkness matery", Template_Text = "StExt_PotionEffect_DarkMasteryDamage_potion_str", ModRarity = 10,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_DarkMasteryDamage, [Value], [Duration])" },
                new ItemMod(142, 15, 50) { ModName = "Potion light mastery", Template_Text = "StExt_PotionEffect_LightMasteryDamage_potion_str", ModRarity = 10,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_LightMasteryDamage, [Value], [Duration])" },
                new ItemMod(143, 15, 50) { ModName = "Potion life mastery", Template_Text = "StExt_PotionEffect_LifeMasteryDamage_potion_str", ModRarity = 10,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_LifeMasteryDamage, [Value], [Duration])" },
                new ItemMod(144, 15, 50) { ModName = "Potion death mastery", Template_Text = "StExt_PotionEffect_DeathMasteryDamage_potion_str", ModRarity = 10,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_DeathMasteryDamage, [Value], [Duration])" },
                new ItemMod(145, 25, 75) { ModName = "Potion icewave", Template_Text = "StExt_PotionEffect_IceWave_potion_str", ModRarity = 10,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_IceWave, [Value], 6)" },
                new ItemMod(146, 25, 75) { ModName = "Potion electrowave", Template_Text = "StExt_PotionEffect_ElectroWave_potion_str", ModRarity = 10,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_ElectroWave, [Value], 1)" },
                new ItemMod(147, 25, 75) { ModName = "Potion poisionwave", Template_Text = "StExt_PotionEffect_PoisWave_potion_str", ModRarity = 10,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_PoisWave, [Value], 5)" },
                new ItemMod(148, 25, 75) { ModName = "Potion firewave", Template_Text = "StExt_PotionEffect_FireWave_potion_str", ModRarity = 10,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_FireWave, [Value], 3)" },
                new ItemMod(149, 25, 75) { ModName = "Potion darkwave", Template_Text = "StExt_PotionEffect_DarkWave_potion_str", ModRarity = 10,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_DarkWave, [Value], 3)" },
                new ItemMod(150, 3, 10) { ModName = "Potion long str debuf", Template_Text = "StExt_PotionEffect_ExtraStrDebuff_potion_str", ModRarity = 15,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_ExtraStr, -[Value], [Duration])" },
                new ItemMod(151, 3, 10) { ModName = "Potion long agi debuf", Template_Text = "StExt_PotionEffect_ExtraAgiDebuff_potion_str", ModRarity = 15,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_ExtraAgi, -[Value], [Duration])" },
                new ItemMod(152, 3, 10) { ModName = "Potion long int debuf", Template_Text = "StExt_PotionEffect_ExtraIntDebuff_potion_str", ModRarity = 15,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_ExtraInt, -[Value], [Duration])" },                
                new ItemMod(153, 10, 25) { ModName = "Potion long golem bonus", Template_Text = "StExt_Str_GolemMasteryDamage", ModRarity = 10,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_GolemMasteryDamage, -[Value], [Duration])" },
                new ItemMod(154, 10, 25) { ModName = "Potion long demon bonus", Template_Text = "StExt_Str_DemonMasteryDamage", ModRarity = 10,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_DemonMasteryDamage, -[Value], [Duration])" },
                new ItemMod(155, 25, 75) { ModName = "Potion extra magic damage", Template_Text = "StExt_PotionEffect_MagicDam_str", ModRarity = 10,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_MagicDam, -[Value], [Duration])" },
                new ItemMod(156, 25, 75) { ModName = "Potion extra orc damage", Template_Text = "StExt_PotionEffect_OrcDam_str", ModRarity = 20,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_OrcDam, -[Value], [Duration])" },
                new ItemMod(157, 25, 75) { ModName = "Potion extra evil damage", Template_Text = "StExt_PotionEffect_EvilDam_str", ModRarity = 20,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_EvilDam, -[Value], [Duration])" },
                new ItemMod(158, 25, 75) { ModName = "Potion extra human damage", Template_Text = "StExt_PotionEffect_HumanDam_str", ModRarity = 20,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_HumanDam, -[Value], [Duration])" },
                new ItemMod(159, 25, 75) { ModName = "Potion extra golem damage", Template_Text = "StExt_PotionEffect_GolemDam_str", ModRarity = 20,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_GolemDam, -[Value], [Duration])" },
                new ItemMod(160, 25, 75) { ModName = "Potion extra animal damage", Template_Text = "StExt_PotionEffect_AnimalDam_str", ModRarity = 20,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_AnimalDam, -[Value], [Duration])" },
                new ItemMod(161, 25, 75) { ModName = "Potion extra undead damage", Template_Text = "StExt_PotionEffect_UndeadDam_str", ModRarity = 20,
                    Template_OnEquip = "StExt_ApplyPotionEffect(StExt_PotionEffect_UndeadDam, -[Value], [Duration])" },


                new ItemMod(201, 1 ,3) {ModName = "Weap Mana regeneration", Template_Text = "StExt_str_JwlrOpt_ManaRegen", ModRarity = 15,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_ManaRegen")};\r\n\t\tStExt_Jwlr_ManaRegen += [Value]", Template_OnUnequip = "StExt_Jwlr_ManaRegen -= [Value]" },
                new ItemMod(202, 5, 15) { ModName = "Weap Summon HP bonus", Template_Text = "StExt_Str_ShowWeapStats_SumHp", ModRarity = 30,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_ShowWeapStats_SumHp")};\r\n\t\tStExt_SumBonus_Hp += [Value]", Template_OnUnequip = "StExt_SumBonus_Hp -= [Value]",
                    ModDataFlag = (int)WeaponModsData.StExt_MagicWeapFlag_Summon },
                new ItemMod(203, 3, 9) { ModName = "Weap Summon stats bonus", Template_Text = "StExt_Str_ShowWeapStats_SumPwr", ModRarity = 30,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_ShowWeapStats_SumPwr")};\r\n\t\tStExt_SumBonus_Stats += [Value]", Template_OnUnequip = "StExt_SumBonus_Stats -= [Value]",
                    ModDataFlag = (int)WeaponModsData.StExt_MagicWeapFlag_Summon},
                new ItemMod(204, 3, 9) { ModName = "Weap Summon protection bonus", Template_Text = "StExt_Str_ShowWeapStats_SumProt", ModRarity = 30,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_ShowWeapStats_SumProt")};\r\n\t\tStExt_SumBonus_Prot += [Value]", Template_OnUnequip = "StExt_SumBonus_Prot -= [Value]",
                    ModDataFlag = (int)WeaponModsData.StExt_MagicWeapFlag_Summon},
                new ItemMod(205, 4, 12) { ModName = "Weap Energy shield regen", Template_Text = "StExt_str_JwlrOpt_EsRegen", ModRarity = 30,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_EsRegen")};\r\n\t\tStExt_Jwlr_EsRegen += [Value]", Template_OnUnequip = "StExt_Jwlr_EsRegen -= [Value]"  },
                new ItemMod(206, 1, 15) { ModName = "Weap Luck", Template_Text = "StExt_Str_ShowWeapStats_Luck", ModRarity = 10,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_ShowWeapStats_Luck")};\r\n\t\tStExt_LootBonus += [Value]", Template_OnUnequip = "StExt_LootBonus -= [Value]" },
                new ItemMod(207, 5, 10) { ModName = "Weap Str + Agility", Template_Text = "StExt_str_JwlrOpt_Stats", ModRarity = 25,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_Stats")};\r\n\t\tnpc_changeattribute(self, atr_dexterity, [Value]);\r\n\t\tnpc_changeattribute(self, atr_strength, [Value])", Template_OnUnequip = "npc_changeattribute(self, atr_dexterity, -[Value]);\r\n\t\tnpc_changeattribute(self, atr_strength, -[Value])" },
                new ItemMod(208, 10, 30) { ModName = "Weap Mana", Template_Text = "name_bonus_manamax", ModRarity = 70,
                    Template_OnEquip = $"{ModEquipInfoString("name_bonus_manamax")};\r\n\t\tself.attribute[3] += [Value]", Template_OnUnequip = "self.attribute[3] -= [Value]" },
                new ItemMod(209, 10, 30) { ModName = "Weap Hp", Template_Text = "name_bonus_hpmax", ModRarity = 70,
                    Template_OnEquip = $"{ModEquipInfoString("name_bonus_hpmax")};\r\n\t\tself.attribute[1] += [Value]", Template_OnUnequip = HpUnequipStr },
                new ItemMod(210, 5, 20) { ModName = "Weap Hp + Mana", Template_Text = "StExt_str_JwlrOpt_StatsHpMp", ModRarity = 35,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_StatsHpMp")};\r\n\t\tself.attribute[1] += [Value];\r\n\t\tself.attribute[3] += [Value]", Template_OnUnequip = $"{HpUnequipStr};\r\n\t\tself.attribute[3] -= [Value]" },
                new ItemMod(211, 5, 20) { ModName = "Weap Int", Template_Text = "StExt_str_JwlrOpt_Int", ModRarity = 20,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_Int")};\r\n\t\trx_changeintquiet([Value])", Template_OnUnequip = "rx_changeintquiet(-[Value])" },
                new ItemMod(212, 15, 35) { ModName = "Weap Energy shield", Template_Text = "StExt_str_JwlrOpt_Es", ModRarity = 10,
                    Template_OnEquip  = $"{ModEquipInfoString("StExt_str_JwlrOpt_Es")};\r\n\t\tStExt_Jwlr_Es += [Value]", Template_OnUnequip = "StExt_Jwlr_Es -= [Value]" },
                new ItemMod(224, 15, 30) { ModName = "Weap Energy shield barrier", Template_Text = "StExt_str_JwlrOpt_EsBarier", ModRarity = 15,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_EsBarier")};\r\n\t\tStExt_Jwlr_EsBarrier += [Value]", Template_OnUnequip = "StExt_Jwlr_EsBarrier -= [Value]" },
                new ItemMod(225, 3, 9) { ModName = "Weap Speed modifier", Template_Text = "StExt_str_JwlrOpt_SpeedMod", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_SpeedMod")};\r\n\t\tadditionalacceleration += [Value]", Template_OnUnequip = "additionalacceleration -= [Value]" },
                new ItemMod(226, 1, 3) { ModName = "Weap 2H bonus", Template_Text = "StExt_str_JwlrOpt_2hBonus", ModRarity = 25,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_2hBonus")};\r\n\t\tb_addfightskill(self, npc_talent_2h, [Value])", Template_OnUnequip = "b_addfightskill(self, npc_talent_2h, -[Value])" },
                new ItemMod(227, 1, 3) { ModName = "Weap 1H bonus", Template_Text = "StExt_str_JwlrOpt_1hBonus", ModRarity = 25,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_1hBonus")};\r\n\t\tb_addfightskill(self, npc_talent_1h, [Value])", Template_OnUnequip = "b_addfightskill(self, npc_talent_1h, -[Value])" },
                new ItemMod(228, 1, 3) { ModName = "Weap Bow bonus", Template_Text = "StExt_str_JwlrOpt_BowBonus", ModRarity = 25,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_BowBonus")};\r\n\t\tb_addfightskill(self, npc_talent_bow, [Value])", Template_OnUnequip = "b_addfightskill(self, npc_talent_bow, -[Value])" },
                new ItemMod(229, 1, 3) { ModName = "Weap Crossbow bonus", Template_Text = "StExt_str_JwlrOpt_CrossbowBonus", ModRarity = 25,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_CrossbowBonus")};\r\n\t\tb_addfightskill(self, npc_talent_crossbow, [Value])", Template_OnUnequip = "b_addfightskill(self, npc_talent_crossbow, -[Value])" },
                new ItemMod(230, 10, 50) { ModName = "Weap Aura bonus", Template_Text = "StExt_str_Jwlr_AuraPwrDist", ModRarity = 20,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_Jwlr_AuraPwrDist")};\r\n\t\tStExt_Jwlr_AuraPwrDist += [Value]", Template_OnUnequip = "StExt_Jwlr_AuraPwrDist -= [Value]" },
                new ItemMod(233, 10, 25) { ModName = "Weap Death magic bonus", Template_Text = "StExt_Str_DeathMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_DeathMasteryDamage")};\r\n\t\tStExt_Jwlr_DeathMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_DeathMasteryDamage -= [Value]" },
                new ItemMod(234, 10, 25) { ModName = "Weap Life magic bonus", Template_Text = "StExt_Str_LifeMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_LifeMasteryDamage")};\r\n\t\tStExt_Jwlr_LifeMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_LifeMasteryDamage -= [Value]" },
                new ItemMod(235, 10, 25) { ModName = "Weap Light magic bonus", Template_Text = "StExt_Str_LightMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_LightMasteryDamage")};\r\n\t\tStExt_Jwlr_LightMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_LightMasteryDamage -= [Value]" },
                new ItemMod(236, 10, 25) { ModName = "Weap Dark magic bonus", Template_Text = "StExt_Str_DarkMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_DarkMasteryDamage")};\r\n\t\tStExt_Jwlr_DarkMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_DarkMasteryDamage -= [Value]" },
                new ItemMod(237, 10, 25) { ModName = "Weap Electric magic bonus", Template_Text = "StExt_Str_ElectricMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_ElectricMasteryDamage")};\r\n\t\tStExt_Jwlr_ElectricMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_ElectricMasteryDamage -= [Value]" },
                new ItemMod(238, 10, 25) { ModName = "Weap Air magic bonus", Template_Text = "StExt_Str_AirMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_AirMasteryDamage")};\r\n\t\tStExt_Jwlr_AirMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_AirMasteryDamage -= [Value]" },
                new ItemMod(239, 10, 25) { ModName = "Weap Earth magic bonus", Template_Text = "StExt_Str_EarthMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_EarthMasteryDamage")};\r\n\t\tStExt_Jwlr_EarthMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_EarthMasteryDamage -= [Value]" },
                new ItemMod(240, 10, 25) { ModName = "Weap Ice magic bonus", Template_Text = "StExt_Str_IceMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_IceMasteryDamage")};\r\n\t\tStExt_Jwlr_IceMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_IceMasteryDamage -= [Value]" },
                new ItemMod(241, 10, 25) { ModName = "Weap Fire magic bonus", Template_Text = "StExt_Str_FireMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_FireMasteryDamage")};\r\n\t\tStExt_Jwlr_FireMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_FireMasteryDamage -= [Value]" },
                new ItemMod(242, 15, 45) { ModName = "Weap Weapon damage", Template_Text = "StExt_Str_WeapDam", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeapDam")};\r\n\t\tStExt_Jwlr_WeapDam += [Value]", Template_OnUnequip = "StExt_Jwlr_WeapDam -= [Value]" },
                new ItemMod(243, 2, 4) { ModName = "Weap Magic power", Template_Text = "StExt_Str_MagicPower", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_MagicPower")};\r\n\t\tcountlearnspell += [Value]", Template_OnUnequip = "countlearnspell -= [Value]" },
                new ItemMod(244, 10, 25) { ModName = "Weap golem magic bonus", Template_Text = "StExt_Str_GolemMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_GolemMasteryDamage")};\r\n\t\tStExt_Jwlr_GolemMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_GolemMasteryDamage -= [Value]" },
                new ItemMod(245, 10, 25) { ModName = "Weap demon magic bonus", Template_Text = "StExt_Str_DemonMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_DemonMasteryDamage")};\r\n\t\tStExt_Jwlr_DemonMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_DemonMasteryDamage -= [Value]" },

                new ItemMod(251, 50, 75) { ModName = "Weap firebolt skill", Template_Text = "StExt_Str_WeaponStat_FireBoltSkillDamage", ModRarity = 10,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeaponStat_FireBoltSkillDamage")};\r\n\t\tStExt_WeaponStat_FireBoltSkillDamage += [Value]", Template_OnUnequip = "StExt_WeaponStat_FireBoltSkillDamage -= [Value]",
                    ModDataFlag = (int)WeaponModsData.StExt_MagicWeapFlag_FireBolt },
                new ItemMod(252, 50, 75) { ModName = "Weap icebolt skill", Template_Text = "StExt_Str_WeaponStat_IceBoltSkillDamage", ModRarity = 10,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeaponStat_IceBoltSkillDamage")};\r\n\t\tStExt_WeaponStat_IceBoltSkillDamage += [Value]", Template_OnUnequip = "StExt_WeaponStat_IceBoltSkillDamage -= [Value]",
                    ModDataFlag = (int)WeaponModsData.StExt_MagicWeapFlag_IceBolt },
                new ItemMod(253, 50, 75) { ModName = "Weap deathbolt skill", Template_Text = "StExt_Str_WeaponStat_NecroBoltSkillDamage", ModRarity = 10,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeaponStat_NecroBoltSkillDamage")};\r\n\t\tStExt_WeaponStat_NecroBoltSkillDamage += [Value]", Template_OnUnequip = "StExt_WeaponStat_NecroBoltSkillDamage -= [Value]",
                    ModDataFlag = (int)WeaponModsData.StExt_MagicWeapFlag_NecroBolt },
                new ItemMod(254, 50, 75) { ModName = "Weap darkbolt skill", Template_Text = "StExt_Str_WeaponStat_DarkBoltSkillDamage", ModRarity = 10,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeaponStat_DarkBoltSkillDamage")};\r\n\t\tStExt_WeaponStat_DarkBoltSkillDamage += [Value]", Template_OnUnequip = "StExt_WeaponStat_DarkBoltSkillDamage -= [Value]",
                    ModDataFlag = (int)WeaponModsData.StExt_MagicWeapFlag_DarkBolt },
                new ItemMod(255, 50, 75) { ModName = "Weap earthbolt skill", Template_Text = "StExt_Str_WeaponStat_EarthBoltSkillDamage", ModRarity = 10,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeaponStat_EarthBoltSkillDamage")};\r\n\t\tStExt_WeaponStat_EarthBoltSkillDamage += [Value]", Template_OnUnequip = "StExt_WeaponStat_EarthBoltSkillDamage -= [Value]",
                    ModDataFlag = (int)WeaponModsData.StExt_MagicWeapFlag_EarthBolt },
                new ItemMod(256, 50, 75) { ModName = "Weap freeze skill", Template_Text = "StExt_Str_WeaponStat_FreezeSkillDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeaponStat_FreezeSkillDamage")};\r\n\t\tStExt_WeaponStat_FreezeSkillDamage += [Value]", Template_OnUnequip = "StExt_WeaponStat_FreezeSkillDamage -= [Value]",
                    ModDataFlag = (int)WeaponModsData.StExt_MagicWeapFlag_Freeze },
                new ItemMod(257, 50, 75) { ModName = "Weap windfist skill", Template_Text = "StExt_Str_WeaponStat_WindFistSkillDamage", ModRarity = 10,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeaponStat_WindFistSkillDamage")};\r\n\t\tStExt_WeaponStat_WindFistSkillDamage += [Value]", Template_OnUnequip = "StExt_WeaponStat_WindFistSkillDamage -= [Value]",
                    ModDataFlag = (int)WeaponModsData.StExt_MagicWeapFlag_WindFist },
                new ItemMod(258, 50, 75) { ModName = "Weap lighting skill", Template_Text = "StExt_Str_WeaponStat_LightingSkillDamage", ModRarity = 10,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeaponStat_LightingSkillDamage")};\r\n\t\tStExt_WeaponStat_LightingSkillDamage += [Value]", Template_OnUnequip = "StExt_WeaponStat_LightingSkillDamage -= [Value]",
                    ModDataFlag = (int)WeaponModsData.StExt_MagicWeapFlag_Lighting },
                new ItemMod(259, 50, 100) { ModName = "Weap heal skill", Template_Text = "StExt_Str_WeaponStat_HealSkill", ModRarity = 15,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeaponStat_HealSkill")};\r\n\t\tStExt_WeaponStat_HealSkill += [Value]", Template_OnUnequip = "StExt_WeaponStat_HealSkill -= [Value]",
                    ModDataFlag = (int)WeaponModsData.StExt_MagicWeapFlag_HealSkill },
                new ItemMod(260, 25, 75) { ModName = "Weap sucklife skill", Template_Text = "StExt_Str_WeaponStat_SuckLifeDamage", ModRarity = 15,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeaponStat_SuckLifeDamage")};\r\n\t\tStExt_WeaponStat_SuckLifeDamage += [Value]", Template_OnUnequip = "StExt_WeaponStat_SuckLifeDamage -= [Value]",
                    ModDataFlag = (int)WeaponModsData.StExt_MagicWeapFlag_SuckLife },
                new ItemMod(261, 1, 3) { ModName = "Weap stun skill", Template_Text = "StExt_Str_WeaponStat_StunSkillChance", ModRarity = 15,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeaponStat_StunSkillChance")};\r\n\t\tStExt_WeaponStat_StunSkillChance += [Value]", Template_OnUnequip = "StExt_WeaponStat_StunSkillChance -= [Value]",
                    ModDataFlag = (int)WeaponModsData.StExt_MagicWeapFlag_Stun },
                new ItemMod(262, 50, 100) { ModName = "Weap undead damage", Template_Text = "StExt_Str_WeaponStat_UndeadDamage", ModRarity = 50,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeaponStat_UndeadDamage")};\r\n\t\tStExt_WeaponStat_UndeadDamage += [Value]", Template_OnUnequip = "StExt_WeaponStat_UndeadDamage -= [Value]" },
                new ItemMod(263, 50, 100) { ModName = "Weap demon damage", Template_Text = "StExt_Str_WeaponStat_DemonDamage", ModRarity = 50,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeaponStat_DemonDamage")};\r\n\t\tStExt_WeaponStat_DemonDamage += [Value]", Template_OnUnequip = "StExt_WeaponStat_DemonDamage -= [Value]" },
                new ItemMod(264, 50, 100) { ModName = "Weap animal damage", Template_Text = "StExt_Str_WeaponStat_AnimalDamage", ModRarity = 50,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeaponStat_AnimalDamage")};\r\n\t\tStExt_WeaponStat_AnimalDamage += [Value]", Template_OnUnequip = "StExt_WeaponStat_AnimalDamage -= [Value]" },
                new ItemMod(265, 35, 75) { ModName = "Weap pois damage", Template_Text = "StExt_Str_WeaponStat_PoisionDotDamage", ModRarity = 25,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeaponStat_PoisionDotDamage")};\r\n\t\tStExt_WeaponStat_PoisionDotDamage += [Value]", Template_OnUnequip = "StExt_WeaponStat_PoisionDotDamage -= [Value]",
                    ModDataFlag = (int)WeaponModsData.StExt_MagicWeapFlag_PoisionDot },
                new ItemMod(266, 35, 75) { ModName = "Weap fire damage", Template_Text = "StExt_Str_WeaponStat_FireDotDamage", ModRarity = 25,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeaponStat_FireDotDamage")};\r\n\t\tStExt_WeaponStat_FireDotDamage += [Value]", Template_OnUnequip = "StExt_WeaponStat_FireDotDamage -= [Value]",
                    ModDataFlag = (int)WeaponModsData.StExt_MagicWeapFlag_FireDot },
                new ItemMod(267, 35, 75) { ModName = "Weap magic damage", Template_Text = "StExt_Str_WeaponStat_MagicDotDamage", ModRarity = 25,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeaponStat_MagicDotDamage")};\r\n\t\tStExt_WeaponStat_MagicDotDamage += [Value]", Template_OnUnequip = "StExt_WeaponStat_MagicDotDamage -= [Value]",
                    ModDataFlag = (int)WeaponModsData.StExt_MagicWeapFlag_MagicDot },
                new ItemMod(268, 35, 75) { ModName = "Weap point damage", Template_Text = "StExt_Str_WeaponStat_PointDotDamage", ModRarity = 35,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeaponStat_PointDotDamage")};\r\n\t\tStExt_WeaponStat_PointDotDamage += [Value]", Template_OnUnequip = "StExt_WeaponStat_PointDotDamage -= [Value]",
                    ModDataFlag = (int)WeaponModsData.StExt_MagicWeapFlag_PointDot },
                new ItemMod(269, 35, 75) { ModName = "Weap edge damage", Template_Text = "StExt_Str_WeaponStat_EdgeDotDamage", ModRarity = 35,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeaponStat_EdgeDotDamage")};\r\n\t\tStExt_WeaponStat_EdgeDotDamage += [Value]", Template_OnUnequip = "StExt_WeaponStat_EdgeDotDamage -= [Value]",
                    ModDataFlag = (int)WeaponModsData.StExt_MagicWeapFlag_EdgeDot },
                new ItemMod(270, 35, 75) { ModName = "Weap blunt damage", Template_Text = "StExt_Str_WeaponStat_BluntDotDamage", ModRarity = 35,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeaponStat_BluntDotDamage")};\r\n\t\tStExt_WeaponStat_BluntDotDamage += [Value]", Template_OnUnequip = "StExt_WeaponStat_BluntDotDamage -= [Value]",
                    ModDataFlag = (int)WeaponModsData.StExt_MagicWeapFlag_BluntDot },
                new ItemMod(271, 50, 100) { ModName = "Weap orc damage", Template_Text = "StExt_Str_WeaponStat_OrcDamage", ModRarity = 35,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeaponStat_OrcDamage")};\r\n\t\tStExt_WeaponStat_OrcDamage += [Value]", Template_OnUnequip = "StExt_WeaponStat_OrcDamage -= [Value]" },
                new ItemMod(272, 50, 100) { ModName = "Weap golem damage", Template_Text = "StExt_Str_WeaponStat_GolemDamage", ModRarity = 35,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeaponStat_GolemDamage")};\r\n\t\tStExt_WeaponStat_GolemDamage += [Value]", Template_OnUnequip = "StExt_WeaponStat_GolemDamage -= [Value]" },
                new ItemMod(273, 50, 100) { ModName = "Weap human damage", Template_Text = "StExt_Str_WeaponStat_HumanDamage", ModRarity = 35,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeaponStat_HumanDamage")};\r\n\t\tStExt_WeaponStat_HumanDamage += [Value]", Template_OnUnequip = "StExt_WeaponStat_HumanDamage -= [Value]" },

                new ItemMod(301, 1 ,3) {ModName = "Armor Mana regeneration", Template_Text = "StExt_str_JwlrOpt_ManaRegen", ModRarity = 15,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_ManaRegen")};\r\n\t\tStExt_Jwlr_ManaRegen += [Value]", Template_OnUnequip = "StExt_Jwlr_ManaRegen -= [Value]"  },
                new ItemMod(302, 5, 15) { ModName = "Armor Summon HP bonus", Template_Text = "StExt_Str_ShowWeapStats_SumHp", ModRarity = 30,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_ShowWeapStats_SumHp")};\r\n\t\tStExt_SumBonus_Hp += [Value]", Template_OnUnequip = "StExt_SumBonus_Hp -= [Value]"  },
                new ItemMod(303, 3, 9) { ModName = "Armor Summon stats bonus", Template_Text = "StExt_Str_ShowWeapStats_SumPwr", ModRarity = 30,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_ShowWeapStats_SumPwr")};\r\n\t\tStExt_SumBonus_Stats += [Value]", Template_OnUnequip = "StExt_SumBonus_Stats -= [Value]"  },
                new ItemMod(304, 3, 9) { ModName = "Armor Summon protection bonus", Template_Text = "StExt_Str_ShowWeapStats_SumProt", ModRarity = 30,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_ShowWeapStats_SumProt")};\r\n\t\tStExt_SumBonus_Prot += [Value]", Template_OnUnequip = "StExt_SumBonus_Prot -= [Value]"  },
                new ItemMod(305, 4, 12) { ModName = "Armor Energy shield regen", Template_Text = "StExt_str_JwlrOpt_EsRegen", ModRarity = 30,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_EsRegen")};\r\n\t\tStExt_Jwlr_EsRegen += [Value]", Template_OnUnequip = "StExt_Jwlr_EsRegen -= [Value]"  },
                new ItemMod(306, 1, 15) { ModName = "Armor Luck", Template_Text = "StExt_Str_ShowWeapStats_Luck", ModRarity = 10,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_ShowWeapStats_Luck")};\r\n\t\tStExt_LootBonus += [Value]", Template_OnUnequip = "StExt_LootBonus -= [Value]" },
                new ItemMod(307, 5, 10) { ModName = "Armor Str + Agility", Template_Text = "StExt_str_JwlrOpt_Stats", ModRarity = 25,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_Stats")};\r\n\t\tnpc_changeattribute(self, atr_dexterity, [Value]);\r\n\t\tnpc_changeattribute(self, atr_strength, [Value])", Template_OnUnequip = "npc_changeattribute(self, atr_dexterity, -[Value]);\r\n\t\tnpc_changeattribute(self, atr_strength, -[Value])" },
                new ItemMod(308, 10, 30) { ModName = "Armor Mana", Template_Text = "name_bonus_manamax", ModRarity = 70,
                    Template_OnEquip = $"{ModEquipInfoString("name_bonus_manamax")};\r\n\t\tself.attribute[3] += [Value]", Template_OnUnequip = "self.attribute[3] -= [Value]" },
                new ItemMod(309, 10, 30) { ModName = "Armor Hp", Template_Text = "name_bonus_hpmax", ModRarity = 70,
                    Template_OnEquip = $"{ModEquipInfoString("name_bonus_hpmax")};\r\n\t\tself.attribute[1] += [Value]", Template_OnUnequip = HpUnequipStr },
                new ItemMod(310, 5, 20) { ModName = "Armor Hp + Mana", Template_Text = "StExt_str_JwlrOpt_StatsHpMp", ModRarity = 35,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_StatsHpMp")};\r\n\t\tself.attribute[1] += [Value];\r\n\t\tself.attribute[3] += [Value]", Template_OnUnequip = $"{HpUnequipStr};\r\n\t\tself.attribute[3] -= [Value]" },
                new ItemMod(311, 5, 20) { ModName = "Armor Int", Template_Text = "StExt_str_JwlrOpt_Int", ModRarity = 50,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_Int")};\r\n\t\trx_changeintquiet([Value])", Template_OnUnequip = "rx_changeintquiet(-[Value])" },
                new ItemMod(312, 15, 35) { ModName = "Armor Energy shield", Template_Text = "StExt_str_JwlrOpt_Es", ModRarity = 50,
                    Template_OnEquip  = $"{ModEquipInfoString("StExt_str_JwlrOpt_Es")};\r\n\t\tStExt_Jwlr_Es += [Value]", Template_OnUnequip = "StExt_Jwlr_Es -= [Value]" },
                new ItemMod(313, 5, 10) { ModName = "Armor Magic + Fire protection", Template_Text = "StExt_str_JwlrOpt_ProtMagic", ModRarity = 15,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_ProtMagic")};\r\n\t\tself.protection[5] += [Value];\r\n\t\tself.protection[3] += [Value]", Template_OnUnequip = "self.protection[5] -= [Value];\r\n\t\tself.protection[3] -= [Value]" },
                new ItemMod(314, 5, 10) { ModName = "Armor Physics protection", Template_Text = "StExt_str_JwlrOpt_ProtWeap", ModRarity = 15,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_ProtWeap")};\r\n\t\tself.protection[6] += [Value];\r\n\t\tself.protection[2] += [Value];\r\n\t\tself.protection[1] += [Value]", Template_OnUnequip = "self.protection[6] -= [Value];\r\n\t\tself.protection[2] -= [Value];\r\n\t\tself.protection[1] -= [Value]" },
                new ItemMod(315, 10, 20) { ModName = "Armor Point protection", Template_Text = "rx_inv_descarmor_prot_point", ModRarity = 40,
                    Template_OnEquip = $"{ModEquipInfoString("rx_inv_descarmor_prot_point")};\r\n\t\tself.protection[6] += [Value]", Template_OnUnequip = "self.protection[6] -= [Value]" },
                new ItemMod(316, 10, 20) { ModName = "Armor Edge protection", Template_Text = "rx_inv_descarmor_prot_edge", ModRarity = 40,
                    Template_OnEquip = $"{ModEquipInfoString("rx_inv_descarmor_prot_edge")};\r\n\t\tself.protection[2] += [Value]", Template_OnUnequip = "self.protection[2] -= [Value]" },
                new ItemMod(317, 10, 20) { ModName = "Armor Blunt protection", Template_Text = "rx_inv_descarmor_prot_blunt", ModRarity = 40,
                    Template_OnEquip = $"{ModEquipInfoString("rx_inv_descarmor_prot_blunt")};\r\n\t\tself.protection[1] += [Value]", Template_OnUnequip = "self.protection[1] -= [Value]" },
                new ItemMod(318, 10, 20) { ModName = "Armor Fly protection", Template_Text = "rx_shield_endurancelevel_str", ModRarity = 40,
                    Template_OnEquip = $"{ModEquipInfoString("rx_shield_endurancelevel_str")};\r\n\t\tself.protection[4] += [Value]", Template_OnUnequip = "self.protection[4] -= [Value]" },
                new ItemMod(319, 10, 20) { ModName = "Armor Fire protection", Template_Text = "rx_inv_descarmor_prot_fire", ModRarity = 40,
                    Template_OnEquip = $"{ModEquipInfoString("rx_inv_descarmor_prot_fire")};\r\n\t\tself.protection[3] += [Value]", Template_OnUnequip = "self.protection[3] -= [Value]" },
                new ItemMod(320, 10, 20) { ModName = "Armor Magic protection", Template_Text = "rx_inv_descarmor_prot_magic", ModRarity = 40,
                    Template_OnEquip = $"{ModEquipInfoString("rx_inv_descarmor_prot_magic")};\r\n\t\tself.protection[5] += [Value]", Template_OnUnequip = "self.protection[5] -= [Value]" },
                new ItemMod(321, 1, 2) { ModName = "Armor Hp regeneration", Template_Text = "StExt_str_JwlrOpt_HpRegen", ModRarity = 25,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_HpRegen")};\r\n\t\tStExt_Jwlr_HpRegen += [Value]", Template_OnUnequip = "StExt_Jwlr_HpRegen -= [Value]"  },
                new ItemMod(322, 1, 1) { ModName = "Armor Max summons", Template_Text = "StExt_Str_ShowWeapStats_SumCount", ModRarity = 15,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_ShowWeapStats_SumCount")};\r\n\t\tStExt_Jwlr_SumCount += [Value]", Template_OnUnequip = "StExt_Jwlr_SumCount -= [Value]"  },
                new ItemMod(323, 1, 2) { ModName = "Armor Dodge chance", Template_Text = "StExt_str_JwlrOpt_Dodge", ModRarity = 40,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_Dodge")};\r\n\t\tStExt_Jwlr_DodgeChance += [Value]", Template_OnUnequip = "StExt_Jwlr_DodgeChance -= [Value]" },
                new ItemMod(324, 15, 30) { ModName = "Armor Energy shield barrier", Template_Text = "StExt_str_JwlrOpt_EsBarier", ModRarity = 30,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_EsBarier")};\r\n\t\tStExt_Jwlr_EsBarrier += [Value]", Template_OnUnequip = "StExt_Jwlr_EsBarrier -= [Value]" },
                new ItemMod(325, 3, 9) { ModName = "Armor Speed modifier", Template_Text = "StExt_str_JwlrOpt_SpeedMod", ModRarity = 10,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_SpeedMod")};\r\n\t\tadditionalacceleration += [Value]", Template_OnUnequip = "additionalacceleration -= [Value]" },
                new ItemMod(326, 1, 3) { ModName = "Armor 2H bonus", Template_Text = "StExt_str_JwlrOpt_2hBonus", ModRarity = 20,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_2hBonus")};\r\n\t\tb_addfightskill(self, npc_talent_2h, [Value])", Template_OnUnequip = "b_addfightskill(self, npc_talent_2h, -[Value])" },
                new ItemMod(327, 1, 3) { ModName = "Armor 1H bonus", Template_Text = "StExt_str_JwlrOpt_1hBonus", ModRarity = 20,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_1hBonus")};\r\n\t\tb_addfightskill(self, npc_talent_1h, [Value])", Template_OnUnequip = "b_addfightskill(self, npc_talent_1h, -[Value])" },
                new ItemMod(328, 1, 3) { ModName = "Armor Bow bonus", Template_Text = "StExt_str_JwlrOpt_BowBonus", ModRarity = 20,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_BowBonus")};\r\n\t\tb_addfightskill(self, npc_talent_bow, [Value])", Template_OnUnequip = "b_addfightskill(self, npc_talent_bow, -[Value])" },
                new ItemMod(329, 1, 3) { ModName = "Armor Crossbow bonus", Template_Text = "StExt_str_JwlrOpt_CrossbowBonus", ModRarity = 20,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_JwlrOpt_CrossbowBonus")};\r\n\t\tb_addfightskill(self, npc_talent_crossbow, [Value])", Template_OnUnequip = "b_addfightskill(self, npc_talent_crossbow, -[Value])" },
                new ItemMod(330, 10, 50) { ModName = "Armor Aura bonus", Template_Text = "StExt_str_Jwlr_AuraPwrDist", ModRarity = 20,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_Jwlr_AuraPwrDist")};\r\n\t\tStExt_Jwlr_AuraPwrDist += [Value]", Template_OnUnequip = "StExt_Jwlr_AuraPwrDist -= [Value]" },
                new ItemMod(331, 1, 1) { ModName = "Armor Poision immune", Template_Text = "StExt_str_Jwlr_PoisionResist", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_Jwlr_PoisionResist")};\r\n\t\tStExt_Jwlr_PoisionResist += [Value]", Template_OnUnequip = "StExt_Jwlr_PoisionResist -= [Value]" },
                new ItemMod(332, 1, 1) { ModName = "Armor Curse immune", Template_Text = "StExt_str_Jwlr_CurseResist", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_str_Jwlr_CurseResist")};\r\n\t\tStExt_Jwlr_CurseResist += [Value]", Template_OnUnequip = "StExt_Jwlr_CurseResist -= [Value]" },
                new ItemMod(333, 10, 25) { ModName = "Armor Death magic bonus", Template_Text = "StExt_Str_DeathMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_DeathMasteryDamage")};\r\n\t\tStExt_Jwlr_DeathMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_DeathMasteryDamage -= [Value]" },
                new ItemMod(334, 10, 25) { ModName = "Armor Life magic bonus", Template_Text = "StExt_Str_LifeMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_LifeMasteryDamage")};\r\n\t\tStExt_Jwlr_LifeMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_LifeMasteryDamage -= [Value]" },
                new ItemMod(335, 10, 25) { ModName = "Armor Light magic bonus", Template_Text = "StExt_Str_LightMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_LightMasteryDamage")};\r\n\t\tStExt_Jwlr_LightMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_LightMasteryDamage -= [Value]" },
                new ItemMod(336, 10, 25) { ModName = "Armor Dark magic bonus", Template_Text = "StExt_Str_DarkMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_DarkMasteryDamage")};\r\n\t\tStExt_Jwlr_DarkMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_DarkMasteryDamage -= [Value]" },
                new ItemMod(337, 10, 25) { ModName = "Armor Electric magic bonus", Template_Text = "StExt_Str_ElectricMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_ElectricMasteryDamage")};\r\n\t\tStExt_Jwlr_ElectricMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_ElectricMasteryDamage -= [Value]" },
                new ItemMod(338, 10, 25) { ModName = "Armor Air magic bonus", Template_Text = "StExt_Str_AirMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_AirMasteryDamage")};\r\n\t\tStExt_Jwlr_AirMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_AirMasteryDamage -= [Value]" },
                new ItemMod(339, 10, 25) { ModName = "Armor Earth magic bonus", Template_Text = "StExt_Str_EarthMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_EarthMasteryDamage")};\r\n\t\tStExt_Jwlr_EarthMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_EarthMasteryDamage -= [Value]" },
                new ItemMod(340, 10, 25) { ModName = "Armor Ice magic bonus", Template_Text = "StExt_Str_IceMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_IceMasteryDamage")};\r\n\t\tStExt_Jwlr_IceMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_IceMasteryDamage -= [Value]" },
                new ItemMod(341, 10, 25) { ModName = "Armor Fire magic bonus", Template_Text = "StExt_Str_FireMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_FireMasteryDamage")};\r\n\t\tStExt_Jwlr_FireMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_FireMasteryDamage -= [Value]" },
                new ItemMod(342, 15, 45) { ModName = "Armor Weapon damage", Template_Text = "StExt_Str_WeapDam", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_WeapDam")};\r\n\t\tStExt_Jwlr_WeapDam += [Value]", Template_OnUnequip = "StExt_Jwlr_WeapDam -= [Value]" },
                new ItemMod(343, 2, 4) { ModName = "Armor Magic power", Template_Text = "StExt_Str_MagicPower", ModRarity = 3,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_MagicPower")};\r\n\t\tcountlearnspell += [Value]", Template_OnUnequip = "countlearnspell -= [Value]" },
                new ItemMod(344, 10, 25) { ModName = "Armor golem magic bonus", Template_Text = "StExt_Str_GolemMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_GolemMasteryDamage")};\r\n\t\tStExt_Jwlr_GolemMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_GolemMasteryDamage -= [Value]" },
                new ItemMod(345, 10, 25) { ModName = "Armor demon magic bonus", Template_Text = "StExt_Str_DemonMasteryDamage", ModRarity = 5,
                    Template_OnEquip = $"{ModEquipInfoString("StExt_Str_DemonMasteryDamage")};\r\n\t\tStExt_Jwlr_DemonMasteryDamage += [Value]", Template_OnUnequip = "StExt_Jwlr_DemonMasteryDamage -= [Value]" },
            };
        }

        private static string ModEquipInfoString(string name) => CommonTemplates.EquipInfoTemplate.Replace("[EquipNameStr]", name);

        private enum WeaponModsData : int
        {
            StExt_MagicWeapFlag_None = 0x0,
            StExt_MagicWeapFlag_Summon = 0x1,
            StExt_MagicWeapFlag_FireBolt = 0x2,
            StExt_MagicWeapFlag_IceBolt = 0x4,
            StExt_MagicWeapFlag_NecroBolt = 0x8,
            StExt_MagicWeapFlag_DarkBolt = 0x10,
            StExt_MagicWeapFlag_EarthBolt = 0x20,
            StExt_MagicWeapFlag_Freeze = 0x40,
            StExt_MagicWeapFlag_WindFist = 0x80,
            StExt_MagicWeapFlag_Lighting = 0x100,
            StExt_MagicWeapFlag_HealSkill = 0x200,
            StExt_MagicWeapFlag_SuckLife = 0x400,
            StExt_MagicWeapFlag_Stun = 0x800,
            StExt_MagicWeapFlag_PoisionDot = 0x1000,
            StExt_MagicWeapFlag_FireDot = 0x2000,
            StExt_MagicWeapFlag_MagicDot = 0x4000,
            StExt_MagicWeapFlag_PointDot = 0x8000,
            StExt_MagicWeapFlag_EdgeDot = 0x10000,
            StExt_MagicWeapFlag_BluntDot = 0x20000
        }

        [Serializable]
        class ItemsModsContainer
        {
            public ItemMod[] ItemMods { get; set; } = new ItemMod[] { };

            public string[] ItemsPrefixes { get; set; } = new string[] { };
            public string[] ItemsAfixes { get; set; } = new string[] { };
            public string[] ItemsSufixes { get; set; } = new string[] { };
        }
    }
}
